pipeline {
    agent {
        node {
            label 'workingDirectory'
            customWorkspace './InventoryManagement'
        }
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }

        }
        stage("Build project") {
            steps {
                sh "gradlew build"
            }
        }
    }
}
