pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }

        }
        stage("Build project") {
            steps {
                sh 'gradle init'
                sh "gradle wrapper build"
            }
        }
    }
}
